import { anchorFromAnalysis } from "./anchor.js";
import {
  ARP_FORM_IDS,
  ARP_MOTIFS,
  ARP_PATTERN_IDS,
  arpChordSemis,
  composeArpSteps,
  degreeToSemis,
  evalLfo,
  expandArpSteps,
  planArpNotes,
  pickArpBars,
  pickArpDivision,
  pickArpForm,
  pickArpLfos,
  pickArpMotifs,
  pickArpPattern,
  sumLfo,
} from "./arp.js";
import {
  generateFromRoles,
  generateVariations,
  renderPreview,
} from "./batch.js";
import {
  applyCoherence,
  applyCoherenceToCards,
  beatMs,
  hzToPitchClass,
  midiToHz,
  quantizePitchedParams,
  roleAllowedSemis,
  roleFundTargetHz,
  snapHzToScale,
  tonicHz,
} from "./coherence.js";
import {
  clampAdditive,
  clampFm,
  clampGranular,
  clampNoise,
  clampNorm,
  clampPhysical,
  clampVoice,
  denormalizeAdditive,
  denormalizeFm,
  denormalizeGranular,
  denormalizeNoise,
  denormalizePhysical,
  denormalizeSubtractive,
  denormalizeVoice,
  durationNormToMs,
  fundNormToHz,
  hzToCutoffNorm,
  hzToFundNorm,
  msToDurationNorm,
  waveFromNorm,
} from "./map.js";
import { renderAdditive } from "./render-additive.js";
import { renderArp } from "./render-arp.js";
import { renderFm } from "./render-fm.js";
import { renderGranular } from "./render-granular.js";
import { renderNoise } from "./render-noise.js";
import { renderPhysical } from "./render-physical.js";
import {
  renderRole,
  sampleMachineParams,
  usesRoleSynth,
} from "./render-role.js";
import { renderSubtractive } from "./render-subtractive.js";
import { renderVoice } from "./render-voice.js";
import {
  createRoleCard,
  defaultFamilyCards,
  isFamilyRoleId,
  applyCardMachine,
  rolePresetPivots,
} from "./roles.js";
import {
  bakeMachine,
  clampMachineParams,
  defaultMachineParams,
  machineSpecFor,
  MACHINE_SPECS_LIST,
} from "./machines.js";
import {
  defaultAdditiveRangesAround,
  defaultFmRangesAround,
  defaultGranularRangesAround,
  defaultNoiseRangesAround,
  defaultPhysicalRangesAround,
  defaultRangesAround,
  defaultVoiceRangesAround,
  expandSymmetric,
  mulberry32,
  rangesFromAdditivePivot,
  rangesFromFmPivot,
  rangesFromGranularPivot,
  rangesFromNoisePivot,
  rangesFromPhysicalPivot,
  rangesFromPivot,
  rangesFromVoicePivot,
  sampleAdditive,
  sampleFm,
  sampleGranular,
  sampleInRange,
  sampleNoise,
  samplePhysical,
  sampleSubtractive,
  sampleVoice,
} from "./sample.js";
import {
  defaultSongCards,
  proposeSongCards,
  SONG_INTENTIONS,
} from "./song.js";
import {
  ADDITIVE_KEYS,
  DEFAULT_ADDITIVE_NORM,
  DEFAULT_FM_NORM,
  DEFAULT_GRANULAR_NORM,
  DEFAULT_NOISE_NORM,
  DEFAULT_PHYSICAL_NORM,
  DEFAULT_SUBTRACTIVE_NORM,
  DEFAULT_VOICE_NORM,
  FAMILY_ROLE_IDS,
  FM_KEYS,
  GRANULAR_KEYS,
  LIVE_ENGINES,
  MVP_ENGINE,
  NOISE_KEYS,
  PHYSICAL_KEYS,
  SUBTRACTIVE_KEYS,
  SYNTH_ENGINE_IDS,
  VOICE_KEYS,
} from "./types.js";

export type { AnalysisAnchorIn } from "./anchor.js";
export type {
  ArpBars,
  ArpFormId,
  ArpLfo,
  ArpLfoShape,
  ArpLfoTarget,
  ArpNotePlan,
  ArpPatternId,
  ArpStep,
  PlanArpOpts,
} from "./arp.js";
export type {
  GenerateFromRolesOpts,
  VariationBatchItem,
  VariationBatchOpts,
} from "./batch.js";
export type {
  CoherenceKind,
  CoherenceOpts,
  ScaleMode,
} from "./coherence.js";
export type { RenderAdditiveResult } from "./render-additive.js";
export type { RenderArpResult } from "./render-arp.js";
export type { RenderFmResult } from "./render-fm.js";
export type { RenderGranularResult } from "./render-granular.js";
export type { RenderNoiseResult } from "./render-noise.js";
export type { RenderPhysicalResult } from "./render-physical.js";
export type { RenderRoleResult } from "./render-role.js";
export type { RenderSubtractiveResult } from "./render-subtractive.js";
export type { RenderVoiceResult } from "./render-voice.js";
export type { SynthRoleCard } from "./roles.js";
export type {
  MachineKnobId,
  MachineKnobSpec,
  MachineParams,
  MachineSpec,
  RolePivots,
} from "./machines.js";
export type { SongIntention } from "./song.js";
export type {
  AdditiveKey,
  AdditiveNorm,
  AdditivePhysical,
  AdditiveRanges,
  ArpMeta,
  FmKey,
  FmNorm,
  FmPhysical,
  FmRanges,
  GranularKey,
  GranularNorm,
  GranularPhysical,
  GranularRanges,
  NoiseKey,
  NoiseNorm,
  NoisePhysical,
  NoiseRanges,
  Norm01,
  ParamRange,
  PhysicalKey,
  PhysicalNorm,
  PhysicalPhysical,
  PhysicalRanges,
  RangeMode,
  SubtractiveKey,
  SubtractiveNorm,
  SubtractivePhysical,
  SubtractiveRanges,
  SynthEngineId,
  SynthMeta,
  SynthMode,
  SynthRoleId,
  VoiceKey,
  VoiceNorm,
  VoicePhysical,
  VoiceRanges,
  WaveShape,
} from "./types.js";

/** Public facade for @glane/audio-synth (ADR-0021). */
export const audioSynth = {
  engines: SYNTH_ENGINE_IDS,
  liveEngines: LIVE_ENGINES,
  mvpEngine: MVP_ENGINE,
  familyRoles: FAMILY_ROLE_IDS,
  songIntentions: SONG_INTENTIONS,
  defaults: DEFAULT_SUBTRACTIVE_NORM,
  defaultsFm: DEFAULT_FM_NORM,
  defaultsNoise: DEFAULT_NOISE_NORM,
  defaultsGranular: DEFAULT_GRANULAR_NORM,
  defaultsAdditive: DEFAULT_ADDITIVE_NORM,
  defaultsPhysical: DEFAULT_PHYSICAL_NORM,
  defaultsVoice: DEFAULT_VOICE_NORM,
  keys: SUBTRACTIVE_KEYS,
  keysFm: FM_KEYS,
  keysNoise: NOISE_KEYS,
  keysGranular: GRANULAR_KEYS,
  keysAdditive: ADDITIVE_KEYS,
  keysPhysical: PHYSICAL_KEYS,
  keysVoice: VOICE_KEYS,
  map: {
    clampNorm,
    clampFm,
    clampNoise,
    clampGranular,
    clampAdditive,
    clampPhysical,
    clampVoice,
    denormalizeSubtractive,
    denormalizeFm,
    denormalizeNoise,
    denormalizeGranular,
    denormalizeAdditive,
    denormalizePhysical,
    denormalizeVoice,
    fundNormToHz,
    hzToFundNorm,
    hzToCutoffNorm,
    msToDurationNorm,
    durationNormToMs,
    waveFromNorm,
  },
  sample: {
    mulberry32,
    sampleInRange,
    expandSymmetric,
    rangesFromPivot,
    rangesFromFmPivot,
    rangesFromNoisePivot,
    rangesFromGranularPivot,
    rangesFromAdditivePivot,
    rangesFromPhysicalPivot,
    rangesFromVoicePivot,
    sampleSubtractive,
    sampleFm,
    sampleNoise,
    sampleGranular,
    sampleAdditive,
    samplePhysical,
    sampleVoice,
    defaultRangesAround,
    defaultFmRangesAround,
    defaultNoiseRangesAround,
    defaultGranularRangesAround,
    defaultAdditiveRangesAround,
    defaultPhysicalRangesAround,
    defaultVoiceRangesAround,
  },
  roles: {
    createRoleCard,
    defaultFamilyCards,
    isFamilyRoleId,
    applyCardMachine,
    rolePresetPivots,
  },
  machines: {
    specs: MACHINE_SPECS_LIST,
    specFor: machineSpecFor,
    defaults: defaultMachineParams,
    clamp: clampMachineParams,
    bake: bakeMachine,
  },
  song: {
    proposeSongCards,
    defaultSongCards,
    intentions: SONG_INTENTIONS,
  },
  coherence: {
    applyCoherence,
    applyCoherenceToCards,
    quantizePitchedParams,
    snapHzToScale,
    tonicHz,
    hzToPitchClass,
    midiToHz,
    beatMs,
    roleFundTargetHz,
    roleAllowedSemis,
  },
  arp: {
    patterns: ARP_PATTERN_IDS,
    forms: ARP_FORM_IDS,
    motifs: ARP_MOTIFS,
    arpChordSemis,
    degreeToSemis,
    composeArpSteps,
    expandArpSteps,
    evalLfo,
    sumLfo,
    planArpNotes,
    pickArpPattern,
    pickArpBars,
    pickArpDivision,
    pickArpForm,
    pickArpMotifs,
    pickArpLfos,
  },
  anchorFromAnalysis,
  renderSubtractive,
  renderFm,
  renderNoise,
  renderGranular,
  renderAdditive,
  renderPhysical,
  renderVoice,
  renderRole,
  sampleMachineParams,
  usesRoleSynth,
  renderArp,
  renderPreview,
  generateVariations,
  generateFromRoles,
} as const;
