#!/usr/bin/env bash
# Interactive production installer for Glane (Docker Compose).
# From repo root on the VPS:
#   bash scripts/install-prod.sh
# Later: bash scripts/update-prod.sh [--pull]

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"
ENV_FILE="$ROOT/.env"

# shellcheck source=lib/prod-env.sh
source "$ROOT/scripts/lib/prod-env.sh"

COMPOSE=(docker compose -f compose.prod.yaml)
COHOST=0

rand_hex() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 32
  else
    head -c 32 /urandom | od -An -tx1 | tr -d ' \n'
  fi
}

escape_regex_host() {
  printf '%s' "$1" | sed 's/\./\\./g'
}

prompt() {
  local var="$1" question="$2" default="${3:-}" value
  if [[ -n "$default" ]]; then
    read -r -p "${question} [${default}]: " value || true
    value="${value:-$default}"
  else
    while true; do
      read -r -p "${question}: " value || true
      [[ -n "$value" ]] && break
      warn "This value is required."
    done
  fi
  printf -v "$var" '%s' "$value"
}

say ""
say "${BLD}Glane — production installer${RST}"
say "Repo root: $ROOT"
say ""
say "Need DNS A/AAAA for app + api hosts."
say "Solo: ports 80/443 free. Cohost: Tadaaa (or other) already owns 80/443."
say ""

need_cmd curl
if ! command -v docker >/dev/null 2>&1 || ! docker compose version >/dev/null 2>&1; then
  die "Docker + Compose required."
fi

prompt domain "Base domain (e.g. example.com)"
prompt app_host "Front host (APP_SERVER_NAME)" "glane.${domain}"
prompt api_host "API host (API_SERVER_NAME)" "glane-api.${domain}"
prompt acme_email "ACME / admin email"
prompt cohost_yn "Cohost behind Tadaaa edge? (y/N)" "N"
case "${cohost_yn}" in
  y|Y|yes|YES) COHOST=1 ;;
  *) COHOST=0 ;;
esac
app_secret="$(rand_hex)"
pg_pass="$(rand_hex)"
mercure_secret="$(rand_hex)"
cors="^https://$(escape_regex_host "$app_host")\$"

cat >"$ENV_FILE" <<EOF
# Generated by scripts/install-prod.sh — DO NOT COMMIT
APP_SERVER_NAME=${app_host}
API_SERVER_NAME=${api_host}
ACME_EMAIL=${acme_email}

APP_SECRET=${app_secret}
APP_NAME=Glane
POSTGRES_DB=glane
POSTGRES_USER=app
POSTGRES_PASSWORD=${pg_pass}
POSTGRES_VERSION=16

CORS_ALLOW_ORIGIN=${cors}
APP_PUBLIC_URL=https://${app_host}
FRONT_URL=https://${app_host}

MERCURE_ENABLED=0
MERCURE_JWT_SECRET=${mercure_secret}
MERCURE_PUBLIC_URL=https://${api_host}/.well-known/mercure
JWT_PASSPHRASE=glane

HTTP_PORT=80
HTTPS_PORT=443
HTTP3_PORT=443

GLANE_COHOST=${COHOST}
WEB_NETWORK=web
EOF
chmod 600 "$ENV_FILE"
ok "Wrote ${ENV_FILE}"

set -a
# shellcheck source=/dev/null
source "$ENV_FILE"
set +a
compose_prod_cmd

if [[ "${GLANE_COHOST:-0}" == "1" ]]; then
  if ! docker network inspect "${WEB_NETWORK:-web}" >/dev/null 2>&1; then
    info "Creating Docker network ${WEB_NETWORK:-web}…"
    docker network create "${WEB_NETWORK:-web}"
    ok "Network ${WEB_NETWORK:-web} created."
  fi
fi

info "Building front (VITE_API_BASE_URL=https://${api_host})…"
rm -rf "$ROOT/node_modules" "$ROOT/apps/web/node_modules"
docker run --rm \
  -v "$ROOT:/repo" \
  -w /repo \
  -e VITE_API_BASE_URL="https://${api_host}" \
  node:22-bookworm \
  bash -lc 'corepack enable && yarn install --frozen-lockfile && yarn --cwd apps/web build'
[[ -f "$ROOT/apps/web/dist/index.html" ]] || die "Front build failed."
ok "Front build ready."

info "Starting stack…"
"${COMPOSE[@]}" up -d --build
ok "Containers started."
# Drop a leftover solo edge if switching to cohost.
if [[ "${GLANE_COHOST:-0}" == "1" ]]; then
  docker compose -f compose.prod.yaml stop edge >/dev/null 2>&1 || true
  docker compose -f compose.prod.yaml rm -f edge >/dev/null 2>&1 || true
fi

info "JWT keys…"
"${COMPOSE[@]}" exec -T php sh -c '
  set -e
  mkdir -p config/jwt var/listens
  if [ ! -f config/jwt/private.pem ]; then
    openssl genpkey -algorithm RSA -out config/jwt/private.pem -pkeyopt rsa_keygen_bits:4096
    openssl rsa -pubout -in config/jwt/private.pem -out config/jwt/public.pem
    chmod 640 config/jwt/private.pem
    chmod 644 config/jwt/public.pem
  fi
'

info "Migrations…"
"${COMPOSE[@]}" exec -T php bin/console doctrine:migrations:migrate --no-interaction
ok "Migrations done."

say ""
say "${BLD}Install complete.${RST}"
say "  Front: https://${app_host}"
say "  API:   https://${api_host}/api/health"
say "  Update later: bash scripts/update-prod.sh --pull"
if [[ "${GLANE_COHOST:-0}" == "1" ]]; then
  say ""
  say "  Cohost: attach Tadaaa edge to network ${WEB_NETWORK:-web} — see .ops/deploy.md"
fi
say ""
